version: '3.9'

services:
  app:
    container_name: app
    image: app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: postgres://postgres:postgres@db:5432/postgres
        SERVER_ADDR: 0.0.0.0:8080
        THREAD_LIMIT: 10
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}